### ISSUE TITLE
CreateVolume failed: snapshot not found in storage backend

### ISSUE THREAD

**Issue by elg0ch0** [LINBIT/linstor-server#151]
Hi,

 I'm getting a 
`CreateVolume failed for pvc-bbc71ad9-b455-4897-afgh-d913113d1261: snapshot not found in storage backend
`
error message when trying to create a PVC from a snapshot.
Environment description:
  - OS: Ubuntu 18.04.4 LTS
  - Kubernetes v17.4
  - Linstor Controller/Satelite: v1.7.1

Manifests used for testing
pvc.yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpvc
spec:
  storageClassName: sc001
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

snapshot.yaml:
```
 apiVersion: snapshot.storage.k8s.io/v1beta1
 kind: VolumeSnapshot
 metadata:
   name: demo-001
 spec:
   volumeSnapshotClassName: sc-snapshot-001
   source:
     persistentVolumeClaimName: hpvc
``` 

recover.yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpvc-restore
spec:
  storageClassName: sc001
  dataSource:
    name: demo-001
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

```
In order to reproduce the error:
```
kubectl create -f pvc.yaml -n ns-t001
kubectl create -f snapshot.yaml -n ns-t001
kubectl create -f restore.yaml -n ns-t001
```
