### ISSUE TITLE
Controller restarts with empty database when using multiple LinstorSatelliteSets

### ISSUE THREAD

**Issue by dkhachyan** [LINBIT/linstor-server#224]
Hi!
We are using linstor over Kubernetes with etcd database
When creating multiple LinstorSatelliteSets for different types of severs, controller restarts with empty database, after creating diskless volume using second LinstorSatelliteSet.

### How to reproduce:

- Create LinstorSatelliteSet 1 
```yaml
apiVersion: piraeus.linbit.com/v1
kind: LinstorSatelliteSet
metadata:
  name: linstor-ns
  namespace: linstor-operator
spec:
  priorityClassName: ""
  sslSecret: 
  drbdRepoCred: ""
  imagePullPolicy: "IfNotPresent"
  satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.11.1
  linstorHttpsClientSecret: ""
  controllerEndpoint: http://linstor-cs.linstor-operator.svc:3370
  automaticStorageType: "None"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - server-1
                  - server-2
                  - server-3
  tolerations: []
  resources: {}
  kernelModuleInjectionMode: "Compile"
  kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-bionic:v9.0.27
  kernelModuleInjectionResources: {}
  storagePools:
    lvmPools:
    - devicePaths:
      - /dev/sda
      name: linstor-lvm
      volumeGroup: linstor-lvm
```

- Create LinstorSatelliteSet 2

```yaml
---
apiVersion: piraeus.linbit.com/v1
kind: LinstorSatelliteSet
metadata:
  name: linstor-ns-nvidia
  namespace: linstor-operator
spec:
  priorityClassName: ""
  sslSecret: 
  drbdRepoCred: ""
  imagePullPolicy: "IfNotPresent"
  satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.11.1
  linstorHttpsClientSecret: ""
  controllerEndpoint: http://linstor-cs.linstor-operator.svc:3370
  automaticStorageType: "None"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - server-4
  tolerations: []
  resources: {}
  kernelModuleInjectionMode: "Compile"
  kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-bionic:v9.0.27
  kernelModuleInjectionResources: {}
  storagePools: {}
```

- Create StorageClass 1

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-hdd
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: storage
  placementCount: "1"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: linstor-lvm
allowedTopologies:
- matchLabelExpressions:
  - key: linbit.com/hostname
    values:
        - server-1
        - server-2
        - server-3

```

- Create StorageClass 2

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linstor-diskless
provisioner: linstor.csi.linbit.com
parameters:
  allowRemoteVolumeAccess: 'true'
  csi.storage.k8s.io/fstype: xfs
  disklessOnRemaining: 'true'
  layerlist: drbd storage
  mountOpts: 'noatime,discard'
  placementCount: '2'
  storagePool: linstor-lvm
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: linbit.com/hostname
    values:
      - server-4
```

- Create some resources with StorageClass 1

- Create some diskless resources with StorageClass 2

- Restart controller

Result:

```
ERROR REPORT 604F3A36-00000-000000
 
============================================================
 
Application: LINBIT�� LINSTOR
Module: Controller
Version: 1.11.1
Build ID: fe95a94d86c66c6c9846a3cf579a1a776f95d3f4
Build time: 2021-01-13T08:34:55+00:00
Error time: 2021-03-15 10:43:05
Node: linstor-cs-controller-dd74d649-5hrt8
 
============================================================
 
Reported error:
===============
 
Category: RuntimeException
Class name: ClassCastException
Class canonical name: java.lang.ClassCastException
Generated at: Method 'load', Source file 'ResourceGroupDbDriver.java', Line #309
 
Error message: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
 
Call backtrace:
 
Method Native Class:Line number
load N com.linbit.linstor.core.objects.ResourceGroupDbDriver:309
load N com.linbit.linstor.core.objects.ResourceGroupDbDriver:57
loadAll N com.linbit.linstor.dbdrivers.etcd.ETCDEngine:144
loadAll N com.linbit.linstor.dbdrivers.AbsDatabaseDriver:100
loadAll N com.linbit.linstor.dbdrivers.DatabaseLoader:248
loadCoreObjects N com.linbit.linstor.core.DbDataInitializer:176
initialize N com.linbit.linstor.core.DbDataInitializer:108
startSystemServices N com.linbit.linstor.core.ApplicationLifecycleManager:87
start N com.linbit.linstor.core.Controller:337
main N com.linbit.linstor.core.Controller:558
 
 
END OF ERROR REPORT.
```

We have database dump before and after crash and can send it via email.
