### ISSUE TITLE
etcd keys count explosion with contiuous rolling-retention snapshots

### ISSUE THREAD

**Issue by khanhngobackend** [LINBIT/linstor-server#324]
Dear team, first of all, I'm hugely grateful for your wonderful work on Linstor storage solution. We are currently using it in tiny-sized production for months with very good experience so far. But we has been hit with an issue described below only after utilizing its snapshoting feature on a new bigger cluster.

Our K8s cluster is on-prem, using Linstor (deployed via Piraeus Operator) as the main persistent storage solution. Our cluster have 12 nodes, each have a single ZFS pool serving all storage requests.

![image](https://user-images.githubusercontent.com/46667187/200226018-1f58cd78-76f0-4a8e-aca5-8a4fcc7e40c5.png)

The above graphs depict continuously growing number of etcd keys (along with values and hence growing db size) almost at the same pace for about ~1 week now. The etcd database in the graph is dedicated to Linstor only, no other services have access to it so Linstor is the sole creator of those data.

We suspect having large number of CSI Snapshots creations/deletions contribute to this phenomenon as our setup currently have multiple PVCs (around 30), each scheduled with hourly snapshots and rolling retention (with the help of https://github.com/FairwindsOps/gemini). The snapshots schedule of all of those PVC are similar:
```yaml
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: &pvc-name data-storage-base-chi-<autofilled>-i-0-0-0
spec:
  template:
    spec:
      volumeSnapshotClassName: k-prod
  persistentVolumeClaim:
    claimName: *pvc-name
  schedule:
  - every: hour
    keep: 4 # not counting the latest (i.e. need to +1)
  - every: 6 hour
    keep: 3 # not counting the latest (i.e. need to +1)
  - every: 1 day
    keep: 6 # not counting the latest (i.e. need to +1)
  - every: 15 day
    keep: 1 # not counting the latest (i.e. need to +1)
  - every: 60 day
    keep: 0 # not counting the latest (i.e. need to +1)
```

FYI, some additional debugging info (all gather at roughly the same time, latest as of this writing) of our K8s-cluster:

Total PVC:
```
> kubectl  get pvc -o name -A | wc -l
33 # some (about 6) are not backed by Listor
```

Total PV:
```
> kubectl get pv -o name | wc -l
33 # some (about 6) are not backed by Listor
```

Total VolumeSnapshot:
```
> kubectl get volumesnapshot -o name -A | wc -l
156
```

Total VolumeSnapshotContent:
```
> kubectl get volumesnapshotcontent -o name | wc -l
156
```

Total Linstor-managed Volumes:
```
> linstor v l | wc -l
27 # already subtracted 4 lines of headers and table borders
```

Total Linstor-managed Snapshots:
```
> linstor s l | wc -l
156  # already subtracted 4 lines of headers and table borders
```

ETCD keys prefix count (sorted):
```
      1 /LINSTOR/DBHISTORY
      1 SPACE_HISTORY/2022-11-02
      1 SPACE_HISTORY/2022-11-03
      1 SPACE_HISTORY/2022-11-04
      1 SPACE_HISTORY/2022-11-05
      1 SPACE_HISTORY/2022-11-06
      1 SPACE_HISTORY/2022-11-07
      1 TRACKING_DATE/
      2 /LINSTOR/VOLUME_GROUPS
      4 /LINSTOR/SEC_CONFIGURATION
      4 /LINSTOR/SEC_DFLT_ROLES
      4 /LINSTOR/SEC_ID_ROLE_MAP
      8 /LINSTOR/SEC_ACCESS_TYPES
      8 /LINSTOR/SEC_IDENTITIES
      8 /LINSTOR/STOR_POOL_DEFINITIONS
     15 /LINSTOR/SEC_TYPES
     16 /LINSTOR/RESOURCE_GROUPS
     20 /LINSTOR/SEC_ROLES
     56 /LINSTOR/NODES
     60 /LINSTOR/SEC_TYPE_RULES
     70 /LINSTOR/NODE_NET_INTERFACES
    120 /LINSTOR/NODE_STOR_POOL
    366 /LINSTOR/VOLUMES
    549 /LINSTOR/LAYER_STORAGE_VOLUMES
    549 /LINSTOR/RESOURCES
    549 /LINSTOR/VOLUME_DEFINITIONS
   1071 /LINSTOR/LAYER_RESOURCE_IDS
   1098 /LINSTOR/RESOURCE_DEFINITIONS
   1695 /LINSTOR/SEC_ACL_MAP
   1863 /LINSTOR/PROPS_CONTAINERS
   4922 /LINSTOR/SEC_OBJECT_PROTECTION
```

**Comment by ghernadi** [comment]
Hello, if you happen to have an older linstor version than 1.20, I assume your issue is related to https://github.com/LINBIT/linstor-server/issues/311. There should also be a non-rc release in the meantime for piraeus as well: https://github.com/piraeusdatastore/piraeus-operator/releases/tag/v1.10.0

**Comment by khanhngobackend** [comment]
![image](https://user-images.githubusercontent.com/46667187/200457329-1a0421c4-64e3-4665-aa9e-173d6f26bbba.png)
![image](https://user-images.githubusercontent.com/46667187/200457418-b251a719-62a4-4982-bb13-6dbc9183707f.png)
We encountered this issue while using Linstor 1.20 and Piraeus Operator 1.10, which I believe are both latest. We encountered the issue #311 before, our team decided it's not worth the risk of dragging K8s control-plane down in cases like that (lots of CRs gets generated hence increasing the load on the APIServer) and also the overhead of storing data via APIServer is huge compared to directly to DB so we switch to standalone etcd DB.

**Comment by ghernadi** [comment]
Would you mind sending me a dump of the database? (mail is in my profile)

If that is not possible, can you tell me more about your setup? Do you for example have auto-snapshot or something alike active? Are old snapshots also automatically deleted? etc...

**Comment by khanhngobackend** [comment]
We have auto-snapshot running every hour, with retention policy (supported by [Gemini](https://github.com/FairwindsOps/gemini)) set as follow:
```
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: &pvc-name data-storage-base-chi-<autofilled>-i-0-0-0
spec:
  template:
    spec:
      volumeSnapshotClassName: k-prod
  persistentVolumeClaim:
    claimName: *pvc-name
  schedule:
  - every: hour
    keep: 4 # not counting the latest (i.e. need to +1)
  - every: 6 hour
    keep: 3 # not counting the latest (i.e. need to +1)
  - every: 1 day
    keep: 6 # not counting the latest (i.e. need to +1)
  - every: 15 day
    keep: 1 # not counting the latest (i.e. need to +1)
  - every: 60 day
    keep: 0 # not counting the latest (i.e. need to +1)
```
Snapshots past retention period are auto-deleted. I can confirm that expired snapshots are correctly remove from both K8s and Linstor. Only metadata stored in etcd keep on growing.
