### ISSUE TITLE
Storage pool with the same name with different zfs backing volume

### ISSUE THREAD

**Issue by kiddouk** [LINBIT/linstor-server#345]
Hi,

after asking on https://github.com/piraeusdatastore/piraeus-operator/issues/443 I dare asking again. I got told that linstor-server consider the failure domain to be at the node level, while I see the domain failure at the disk level.

Question for the developers, is that so? Even considering that disk have a (I think) higher rate of failure ?

My idea (if you read the original post) is that I would like to balance my 3 replicas for each of my volume on 2 nodes with each 2 SSD backed by 1 ZFS pool each. 2 Nodes/4 ZFS pools into one StoragePool. 

Is this use case far out what linstor-server could provide ?

### Somewhat original message

I have 2 nodes that have 1 SSD each. Each SSD has a ZFS storage pool. Naturally, I create 2 Linstor Storage Pool and use it.

```
kubectl linstor storage-pool create zfsthin node1 genericpool storage1
kubectl linstor storage-pool create zfsthin node2 genericpool storage2

kubect get sc linstor -o yaml

allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: linstor
  uid: 77a537a8-b277-4944-b4a6-04a9e24cfd0c
parameters:
  autoPlace: "2"
  storagePool: generic-pool
provisioner: linstor.csi.linbit.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

So far so good.

Now, I want to add a second SSD to node1. I create a new ZFS storagepool on the whole disk. I want to create a new Linstor Storage Pool on node1 so that I can use my new disk with` "autoplace: 3"`.

```
kubectl linstor storage-pool create zfsthin node1 genericpool storage3

ERROR:
    Node: node1, Storage pool name: genericpool already exists.
```

Why can't I do this (beside the obvious database Index that requires unicity of host/poolname) ?

I could RAID my ZFS pools but I want to enjoy the autoplace: 3

What if I add an another ZFS pool to node2 and have 4 disks in generic-pool with autoplace: 3 ?

Thanks,
