### ISSUE TITLE
linstor resource make-available failed due to an unknown exception on shared-lun

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#351]
Hi, I created shared LUN and trying to use it from Kubernetes:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-vm0-boot
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: linstor-shared-lun
  volumeMode: Block
```
