### ISSUE TITLE
Linstor, installed via Piraeus operator in Kubernetes cluster, disables LVM monitoring

### ISSUE THREAD

**Issue by dmrub** [LINBIT/linstor-server#396]
Priaeus operator: v2.3.0
Piraeus server: v1.25.1
Linstor is installed with the following satellite configuration
```yaml
---    
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: linstor-fast
spec:
  internalTLS:
    certManager:
      name: linstor-internal-ca
      kind: Issuer
  storagePools:
    - name: vg00-linstor
      lvmThinPool:
        volumeGroup: vg00
        thinPool: linstor

```
After the installation on all nodes belonging to the cluster, I see the following error message from dmeventd:
```
Mär 22 14:33:01 k8s-a-m2 dmeventd[510]: dmeventd ready for processing.
Mär 22 14:33:01 k8s-a-m2 lvm[510]: Monitoring thin pool vg00-linstor.
Mär 22 14:46:05 k8s-a-m2 lvm[510]: Cannot resize logical volume vg00/linstor with active component LV(s).
Mär 22 14:46:06 k8s-a-m2 lvm[510]: Failed command for vg00-linstor.
Mär 22 14:46:06 k8s-a-m2 lvm[510]: Invalid target type.
Mär 22 14:46:06 k8s-a-m2 lvm[510]: device-mapper: waitevent ioctl on  LVM-GESmqya2yM2SsNLq8tV8e7azMA8NDvGNVQjBN30HnjXCyjTzUzt36tBA6mPeE112-tpool failed: No such device or address
Mär 22 14:46:06 k8s-a-m2 lvm[510]: vg00-linstor disappeared, detaching.
Mär 22 14:46:06 k8s-a-m2 dmeventd[510]: No longer monitoring thin pool vg00-linstor.
```
This means that LVM does not resize thin volumes, even if automatic expansion is enabled:
```
root@k8s-a-m2:/home/devops-core# lvmconfig --type diff
activation {
	snapshot_autoextend_threshold=75
	thin_pool_autoextend_threshold=70
}
devices {
	issue_discards=1
}

root@k8s-a-m2:/home/devops-core# lvs
  LV                                             VG   Attr       LSize  Pool    Origin Data%  Meta%  Move Log Cpy%Sync Convert
  linstor                                        vg00 twi-aotzD- 20,00g                100,00 44,20                           
  pvc-0d060605-76be-41d6-bd5d-ddb55fbae354_00000 vg00 Vwi-aotz--  1,00g linstor        4,80                                   
  pvc-4432e6da-9910-4b8d-a9c2-0e9d95ddeb02_00000 vg00 Vwi-a-tz-- 10,00g linstor        97,85                                  
  pvc-6f8e6887-7cd4-49a7-a2d9-017682f99632_00000 vg00 Vwi-aotz-- 10,00g linstor        99,52                                  
  pvc-7cabbd65-2073-4f84-8d0a-4f70f1d98a46_00000 vg00 Vwi-a-tz-- 10,00g linstor        2,07                                   
  root                                           vg00 -wi-ao---- 60,00g
```

I assume that Linstor should not deactivate monitoring.
