### ISSUE TITLE
Wrong linstor_volume_state metrics for non-replicated volumes

### ISSUE THREAD

**Issue by maxpain** [LINBIT/linstor-server#420]
Hello. I use two storage classes in my cluster:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-lvm-local
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/storagePool: nvme-lvm
  linstor.csi.linbit.com/layerList: "storage"
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-lvm-replicated-async
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/storagePool: nvme-lvm
  linstor.csi.linbit.com/autoPlace: "2"
  linstor.csi.linbit.com/layerList: "drbd storage"
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
  property.linstor.csi.linbit.com/DrbdOptions/Net/protocol: "A"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

<img width="1255" alt="image" src="https://github.com/user-attachments/assets/2a74402a-a101-4db9-8452-7a3650cb509f">

The `linstor_volume_state` metric shows `4` and `1` for `drbd volumes`, but `-1` for `non-drbd` volumes. Is it intended behavior, or is it a bug? I want the grafana dashboard to be green :)

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/276f3438-be7c-4566-b06c-3afb51df06b8">
