### ISSUE TITLE
Snapshot Deletion Errors with Velero and Linstor’s Snapshot Shipping

### ISSUE THREAD

**Issue by boedy** [LINBIT/linstor-server#441]
I’m not sure if this should be posted here or in the CSI repo, so please forgive me if this is the wrong place.

I’ve been experimenting with Velero and Linstor’s snapshot shipping feature. Initially, I was confused about the configuration. It turns out that Velero’s data mover must be disabled, or else both Linstor and Velero’s Kopia start shipping snapshot data to S3. I believe this may cause a race condition, potentially leading to [this issue](https://github.com/LINBIT/linstor-server/issues/440).

This requirement doesn’t seem to be clearly documented, so it might be worth adding a note about it somewhere. Perhaps in the article "[Backing up a Kubernetes Deployment Using Velero & LINBIT SDS](https://linbit.com/blog/using-velero-linbit-sds-to-back-up-restore-a-kubernetes-deployment/)"

## Problem: Snapshot Deletion Errors
Once I disabled snapshotMoveData, I wanted to test how incremental snapshots are handled. I created a backup schedule to take a snapshot every 2 minutes, with a retention of 10 minutes:

**Backup schedule**
```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: sample-schedule
  namespace: velero
spec:
  schedule: "*/2 * * * *"
  template:
    includedNamespaces:
      - default
    includedResources:
      - '*'
    storageLocation: default
    ttl: "0h10m0s"
    # snapshotMoveData: true
```

Initially, everything worked fine, but once the first snapshots started expiring, the CSI snapshot container began throwing errors.

**Example error log:**
`
E0303 22:00:41.509762       1 snapshot_controller_base.go:361] could not sync content "snapcontent-4e7c6cdd-a156-41e0-a1b9-03516af60b1e": failed to delete snapshot "snapcontent-4e7c6cdd-a156-41e0-a1b9-03516af60b1e", err: failed to delete snapshot content snapcontent-4e7c6cdd-a156-41e0-a1b9-03516af60b1e: "rpc error: code = Internal desc = unable to delete snapshot snapshot-4e7c6cdd-a156-41e0-a1b9-03516af60b1e: failed to delete backup pvc-b5ca1c80-f58b-4aa6-bd9f-279ee235ebc2_back_20250303_215030^snapshot-4e7c6cdd-a156-41e0-a1b9-03516af60b1e: Message: 'pvc-b5ca1c80-f58b-4aa6-bd9f-279ee235ebc2_back_20250303_215030^snapshot-4e7c6cdd-a156-41e0-a1b9-03516af60b1e.meta should be deleted, but at least pvc-b5ca1c80-f58b-4aa6-bd9f-279ee235ebc2_back_20250303_215231^snapshot-00255afe-6945-4035-a04a-28b4b55cd21c.meta is referencing it. Use --cascading to delete recursively'"
`

For full details, see the [csi-snapshotter.log](https://github.com/user-attachments/files/19163370/csi-snapshotter.log).

**Snapshot Class Configuration**
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: piraeus-snapshots
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: linstor.csi.linbit.com
deletionPolicy: Retain
parameters:
  snap.linstor.csi.linbit.com/type: S3
  snap.linstor.csi.linbit.com/remote-name: velero-backup
  snap.linstor.csi.linbit.com/allow-incremental: "true"
  snap.linstor.csi.linbit.com/delete-local: "false"
  snap.linstor.csi.linbit.com/s3-bucket: **redacted**
  snap.linstor.csi.linbit.com/s3-endpoint: **redacted**
  snap.linstor.csi.linbit.com/s3-signing-region: **redacted**
  snap.linstor.csi.linbit.com/s3-use-path-style: "true"
  csi.storage.k8s.io/snapshotter-secret-name: linstor-csi-s3-access
  csi.storage.k8s.io/snapshotter-secret-namespace: velero
```

**Question**
- Are these errors expected when using incremental snapshots in combination with Velero, or could this be a bug?
- Could it be that Velero continuously attempts to delete snapshots, leading to these errors?

**Bonus Question**
With Velero, it’s common to have multiple backup schedules with varying backup intervals and TTLs. For example:

```text
Interval: Hourly    ttl: 72 hours
Interval: Daily     ttl: 7 days
Interval: Weekly    ttl: 4 weeks
Interval: Monthly   ttl: 4 months
```

How does Linstor’s CSI handle such cases?
   - When does it decide to create a full backup versus an incremental backup?
   - If multiple schedules target the same volume, how does it determine which snapshots to retain or delete?
